<?php
/**
 * EventAttributes
 *
 * PHP version 5
 *
 * @category Class
 * @package  ProcessMaker\PMIO
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ProcessMaker API
 *
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine API that is designed to be used as a microservice to support enterprise cloud applications. The current Alpha 1.0 version supports most of the descriptive classes of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ProcessMaker\PMIO\Model;

use \ArrayAccess;

/**
 * EventAttributes Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     ProcessMaker\PMIO
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EventAttributes implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Event_attributes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'name' => 'string',
        'description' => 'string',
        'process_id' => 'string',
        'message_id' => 'int',
        'type' => 'string',
        'definition' => 'string',
        'interrupting' => 'bool',
        'condition' => 'string',
        'time' => 'string',
        'duration' => 'string',
        'cycle' => 'string',
        'attached_to_task_id' => 'string',
        'ref_id' => 'string',
        'created_at' => 'string',
        'updated_at' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'name' => 'name',
        'description' => 'description',
        'process_id' => 'process_id',
        'message_id' => 'message_id',
        'type' => 'type',
        'definition' => 'definition',
        'interrupting' => 'interrupting',
        'condition' => 'condition',
        'time' => 'time',
        'duration' => 'duration',
        'cycle' => 'cycle',
        'attached_to_task_id' => 'attached_to_task_id',
        'ref_id' => 'ref_id',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'name' => 'setName',
        'description' => 'setDescription',
        'process_id' => 'setProcessId',
        'message_id' => 'setMessageId',
        'type' => 'setType',
        'definition' => 'setDefinition',
        'interrupting' => 'setInterrupting',
        'condition' => 'setCondition',
        'time' => 'setTime',
        'duration' => 'setDuration',
        'cycle' => 'setCycle',
        'attached_to_task_id' => 'setAttachedToTaskId',
        'ref_id' => 'setRefId',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'name' => 'getName',
        'description' => 'getDescription',
        'process_id' => 'getProcessId',
        'message_id' => 'getMessageId',
        'type' => 'getType',
        'definition' => 'getDefinition',
        'interrupting' => 'getInterrupting',
        'condition' => 'getCondition',
        'time' => 'getTime',
        'duration' => 'getDuration',
        'cycle' => 'getCycle',
        'attached_to_task_id' => 'getAttachedToTaskId',
        'ref_id' => 'getRefId',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const TYPE_START = 'START';
    const TYPE_END = 'END';
    const TYPE_INTERMEDIATE_CATCH = 'INTERMEDIATE_CATCH';
    const TYPE_INTERMEDIATE_THROW = 'INTERMEDIATE_THROW';
    const TYPE_BOUNDARY = 'BOUNDARY';
    const TYPE_IMPLICIT_THROW = 'IMPLICIT_THROW';
    const DEFINITION_NONE = 'NONE';
    const DEFINITION_CANCEL = 'CANCEL';
    const DEFINITION_COMPENSATION = 'COMPENSATION';
    const DEFINITION_ERROR = 'ERROR';
    const DEFINITION_ESCALATION = 'ESCALATION';
    const DEFINITION_MESSAGE = 'MESSAGE';
    const DEFINITION_LINK = 'LINK';
    const DEFINITION_SIGNAL = 'SIGNAL';
    const DEFINITION_TERMINATE = 'TERMINATE';
    const DEFINITION_TIMER = 'TIMER';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_START,
            self::TYPE_END,
            self::TYPE_INTERMEDIATE_CATCH,
            self::TYPE_INTERMEDIATE_THROW,
            self::TYPE_BOUNDARY,
            self::TYPE_IMPLICIT_THROW,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getDefinitionAllowableValues()
    {
        return [
            self::DEFINITION_NONE,
            self::DEFINITION_CANCEL,
            self::DEFINITION_COMPENSATION,
            self::DEFINITION_ERROR,
            self::DEFINITION_ESCALATION,
            self::DEFINITION_MESSAGE,
            self::DEFINITION_LINK,
            self::DEFINITION_SIGNAL,
            self::DEFINITION_TERMINATE,
            self::DEFINITION_TIMER,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['process_id'] = isset($data['process_id']) ? $data['process_id'] : null;
        $this->container['message_id'] = isset($data['message_id']) ? $data['message_id'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['definition'] = isset($data['definition']) ? $data['definition'] : null;
        $this->container['interrupting'] = isset($data['interrupting']) ? $data['interrupting'] : null;
        $this->container['condition'] = isset($data['condition']) ? $data['condition'] : null;
        $this->container['time'] = isset($data['time']) ? $data['time'] : null;
        $this->container['duration'] = isset($data['duration']) ? $data['duration'] : null;
        $this->container['cycle'] = isset($data['cycle']) ? $data['cycle'] : null;
        $this->container['attached_to_task_id'] = isset($data['attached_to_task_id']) ? $data['attached_to_task_id'] : null;
        $this->container['ref_id'] = isset($data['ref_id']) ? $data['ref_id'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['name'] === null) {
            $invalid_properties[] = "'name' can't be null";
        }
        if ($this->container['process_id'] === null) {
            $invalid_properties[] = "'process_id' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalid_properties[] = "'type' can't be null";
        }
        $allowed_values = array("START", "END", "INTERMEDIATE_CATCH", "INTERMEDIATE_THROW", "BOUNDARY", "IMPLICIT_THROW");
        if (!in_array($this->container['type'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'type', must be one of #{allowed_values}.";
        }

        if ($this->container['definition'] === null) {
            $invalid_properties[] = "'definition' can't be null";
        }
        $allowed_values = array("NONE", "CANCEL", "COMPENSATION", "ERROR", "ESCALATION", "MESSAGE", "LINK", "SIGNAL", "TERMINATE", "TIMER");
        if (!in_array($this->container['definition'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'definition', must be one of #{allowed_values}.";
        }

        if (!is_null($this->container['ref_id']) && (strlen($this->container['ref_id']) > 255)) {
            $invalid_properties[] = "invalid value for 'ref_id', the character length must be smaller than or equal to 255.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['name'] === null) {
            return false;
        }
        if ($this->container['process_id'] === null) {
            return false;
        }
        if ($this->container['type'] === null) {
            return false;
        }
        $allowed_values = array("START", "END", "INTERMEDIATE_CATCH", "INTERMEDIATE_THROW", "BOUNDARY", "IMPLICIT_THROW");
        if (!in_array($this->container['type'], $allowed_values)) {
            return false;
        }
        if ($this->container['definition'] === null) {
            return false;
        }
        $allowed_values = array("NONE", "CANCEL", "COMPENSATION", "ERROR", "ESCALATION", "MESSAGE", "LINK", "SIGNAL", "TERMINATE", "TIMER");
        if (!in_array($this->container['definition'], $allowed_values)) {
            return false;
        }
        if (strlen($this->container['ref_id']) > 255) {
            return false;
        }
        return true;
    }


    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets process_id
     * @return string
     */
    public function getProcessId()
    {
        return $this->container['process_id'];
    }

    /**
     * Sets process_id
     * @param string $process_id
     * @return $this
     */
    public function setProcessId($process_id)
    {
        $this->container['process_id'] = $process_id;

        return $this;
    }

    /**
     * Gets message_id
     * @return int
     */
    public function getMessageId()
    {
        return $this->container['message_id'];
    }

    /**
     * Sets message_id
     * @param int $message_id
     * @return $this
     */
    public function setMessageId($message_id)
    {
        $this->container['message_id'] = $message_id;

        return $this;
    }

    /**
     * Gets type
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     * @param string $type
     * @return $this
     */
    public function setType($type)
    {
        $allowed_values = array('START', 'END', 'INTERMEDIATE_CATCH', 'INTERMEDIATE_THROW', 'BOUNDARY', 'IMPLICIT_THROW');
        if (!in_array($type, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'type', must be one of 'START', 'END', 'INTERMEDIATE_CATCH', 'INTERMEDIATE_THROW', 'BOUNDARY', 'IMPLICIT_THROW'");
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets definition
     * @return string
     */
    public function getDefinition()
    {
        return $this->container['definition'];
    }

    /**
     * Sets definition
     * @param string $definition
     * @return $this
     */
    public function setDefinition($definition)
    {
        $allowed_values = array('NONE', 'CANCEL', 'COMPENSATION', 'ERROR', 'ESCALATION', 'MESSAGE', 'LINK', 'SIGNAL', 'TERMINATE', 'TIMER');
        if (!in_array($definition, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'definition', must be one of 'NONE', 'CANCEL', 'COMPENSATION', 'ERROR', 'ESCALATION', 'MESSAGE', 'LINK', 'SIGNAL', 'TERMINATE', 'TIMER'");
        }
        $this->container['definition'] = $definition;

        return $this;
    }

    /**
     * Gets interrupting
     * @return bool
     */
    public function getInterrupting()
    {
        return $this->container['interrupting'];
    }

    /**
     * Sets interrupting
     * @param bool $interrupting
     * @return $this
     */
    public function setInterrupting($interrupting)
    {
        $this->container['interrupting'] = $interrupting;

        return $this;
    }

    /**
     * Gets condition
     * @return string
     */
    public function getCondition()
    {
        return $this->container['condition'];
    }

    /**
     * Sets condition
     * @param string $condition
     * @return $this
     */
    public function setCondition($condition)
    {
        $this->container['condition'] = $condition;

        return $this;
    }

    /**
     * Gets time
     * @return string
     */
    public function getTime()
    {
        return $this->container['time'];
    }

    /**
     * Sets time
     * @param string $time
     * @return $this
     */
    public function setTime($time)
    {
        $this->container['time'] = $time;

        return $this;
    }

    /**
     * Gets duration
     * @return string
     */
    public function getDuration()
    {
        return $this->container['duration'];
    }

    /**
     * Sets duration
     * @param string $duration
     * @return $this
     */
    public function setDuration($duration)
    {
        $this->container['duration'] = $duration;

        return $this;
    }

    /**
     * Gets cycle
     * @return string
     */
    public function getCycle()
    {
        return $this->container['cycle'];
    }

    /**
     * Sets cycle
     * @param string $cycle
     * @return $this
     */
    public function setCycle($cycle)
    {
        $this->container['cycle'] = $cycle;

        return $this;
    }

    /**
     * Gets attached_to_task_id
     * @return string
     */
    public function getAttachedToTaskId()
    {
        return $this->container['attached_to_task_id'];
    }

    /**
     * Sets attached_to_task_id
     * @param string $attached_to_task_id
     * @return $this
     */
    public function setAttachedToTaskId($attached_to_task_id)
    {
        $this->container['attached_to_task_id'] = $attached_to_task_id;

        return $this;
    }

    /**
     * Gets ref_id
     * @return string
     */
    public function getRefId()
    {
        return $this->container['ref_id'];
    }

    /**
     * Sets ref_id
     * @param string $ref_id Set as XML object ID if imported from BPMN file or can be optionally set when object added via API. Used to optionally refer object by ref_id instead of using its UUID.
     * @return $this
     */
    public function setRefId($ref_id)
    {
        if (strlen($ref_id) > 255) {
            throw new \InvalidArgumentException('invalid length for $ref_id when calling EventAttributes., must be smaller than or equal to 255.');
        }
        $this->container['ref_id'] = $ref_id;

        return $this;
    }

    /**
     * Gets created_at
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     * @param string $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     * @param string $updated_at
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\ProcessMaker\PMIO\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\ProcessMaker\PMIO\ObjectSerializer::sanitizeForSerialization($this));
    }
}


